### ISSUE TITLE
puerto 8005 ocupado

### ISSUE THREAD

**Issue by poolebu** [poolebu/catwizard_tomcat_node#2]
```
Mar 23, 2015 5:34:30 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 1949 ms
Mar 23, 2015 5:34:30 PM org.apache.catalina.core.StandardServer await
SEVERE: StandardServer.await: create[localhost:8005]: 
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:353)
	at java.net.ServerSocket.bind(ServerSocket.java:336)
	at java.net.ServerSocket.<init>(ServerSocket.java:202)
	at org.apache.catalina.core.StandardServer.await(StandardServer.java:427)
	at org.apache.catalina.startup.Catalina.await(Catalina.java:777)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:723)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:321)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:455)
Mar 23, 2015 5:34:30 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-bio-8081"]
Mar 23, 2015 5:34:30 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["ajp-bio-8009"]
Mar 23, 2015 5:34:30 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service Catalina
Mar 23, 2015 5:34:30 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-bio-8081"]
Mar 23, 2015 5:34:30 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-bio-8081"]
Mar 23, 2015 5:34:30 PM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["ajp-bio-8009"]
Mar 23, 2015 5:34:30 PM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["ajp-bio-8009"]
```

**Comment by poolebu** [comment]
Este puerto se configura en el conf/server.xml

en la primera linea

    <Server port="8005" shutdown="SHUTDOWN">

**Comment by poolebu** [comment]
Agregada funcionalidad que le pasas el puerto
